/*
  Evercraft Idle - Russian localization overlay dictionary
  Non-invasive DOM translation layer for built/minified web bundle.
*/

var cnItems = {
  _OTHER_: [],

  // Core UI
  "Save": "Сохранить",
  "Export": "Экспорт",
  "Import": "Импорт",
  "Settings": "Настройки",
  "Achievements": "Достижения",
  "Statistics": "Статистика",
  "Changelog": "Список изменений",
  "Hotkeys": "Горячие клавиши",
  "Options": "Параметры",
  "Saves": "Сохранения",
  "Default Save": "Слот по умолчанию",
  "Delete": "Удалить",
  "Duplicate": "Дублировать",
  "Edit Name": "Изменить имя",
  "Are you sure?": "Вы уверены?",
  "Yes": "Да",
  "No": "Нет",
  "Cancel": "Отмена",
  "Info": "Инфо",
  "Appearance": "Внешний вид",
  "Theme": "Тема",
  "Classic": "Классика",
  "Default": "По умолчанию",
  "default": "по умолчанию",
  "Configurable": "Настраиваемо",
  "ALL": "ВСЕ",
  "All": "Все",
  "None": "Нет",
  "ENABLED": "ВКЛ",
  "DISABLED": "ВЫКЛ",
  "AUTO": "АВТО",
  "Mute": "Выключить звук",
  "Unmute": "Включить звук",
  "Join the Discord!": "Присоединяйтесь к Discord!",
  "Join Discord": "Перейти в Discord",
  "Community": "Сообщество",

  // Save / import-export flows
  "Export Save": "Экспорт сохранения",
  "Import Save": "Импорт сохранения",
  "Copy to Clipboard": "Скопировать в буфер",
  "Paste from Clipboard": "Вставить из буфера",
  "Download File": "Скачать файл",
  "Load File": "Загрузить файл",
  "Export to file": "Экспорт в файл",
  "Import file": "Импорт из файла",
  "Import clipboard": "Импорт из буфера",
  "Import from file": "Импортировано из файла",
  "Imported from file": "Импортировано из файла",
  "Exported to clipboard": "Экспортировано в буфер",
  "Hard Reset": "Полный сброс",
  "Danger Zone": "Опасная зона",
  "This will permanently delete all progress.": "Это навсегда удалит весь прогресс.",

  // Tabs and systems
  "Crafting": "Крафт",
  "Foundries": "Литейные",
  "Combat": "Бой",
  "Combat Upgrades": "Боевые улучшения",
  "Core Upgrades": "Ключевые улучшения",
  "Artifacts": "Артефакты",
  "Singularity": "Сингулярность",
  "Singularities": "Сингулярности",
  "Skill Tree": "Дерево навыков",
  "Mastery": "Мастерство",
  "Gem Mastery": "Мастерство самоцветов",
  "Combat Mastery": "Мастерство боя",
  "Shard Log": "Журнал осколков",
  "How It Works": "Как это работает",

  // Resources and labels
  "Mana": "Мана",
  "Current Mana": "Текущая мана",
  "Experience": "Опыт",
  "Gem": "Самоцвет",
  "Gems": "Самоцветы",
  "Prisms": "Призмы",
  "Prism Power": "Сила призм",
  "Prism Effectiveness": "Эффективность призм",
  "Prism Memory": "Память призм",
  "Artifacts": "Артефакты",
  "Artifact Memory": "Память артефактов",
  "Artifact Effectiveness": "Эффективность артефактов",
  "Energy Cores": "Энергоядра",
  "Energy Core Drops": "Выпадение энергоядер",
  "Shards": "Осколки",
  "No shards found yet...": "Осколки пока не найдены...",
  "shards = level up": "осколки = повышение уровня",

  // Stats and actions
  "Speed": "Скорость",
  "Yield": "Выход",
  "Generation": "Генерация",
  "Sort": "Сортировка",
  "Attack": "Атака",
  "Attack Speed": "Скорость атаки",
  "Damage": "Урон",
  "Damage:": "Урон:",
  "Health": "Здоровье",
  "HP": "HP",
  "HP/s": "HP/с",
  "HP/s regen": "Реген HP/с",
  "max HP": "Макс. HP",
  "Faster Revive": "Быстрее возрождение",
  "Reviving in...": "Возрождение через...",
  "DEFEATED": "ПОРАЖЕНИЕ",
  "You": "Вы",
  "VS": "VS",
  "Enemy #": "Враг #",
  "Highest Enemy": "Макс. враг",
  "Character Locked": "Персонаж заблокирован",
  "Unlock Combat": "Открыть бой",
  "Unlock Mastery": "Открыть мастерство",
  "Unlocks the Mastery system": "Открывает систему мастерства",
  "Auto Combat": "Автобой",
  "Auto-unlock & upgrades": "Авто-открытие и улучшения",

  // Crafting actions and tooltips
  "Select Recipe": "Выбрать рецепт",
  "Stop Production": "Остановить производство",
  "Upgrade": "Улучшить",
  "Requires": "Требуется",
  "Cost": "Стоимость",
  "Cost:": "Стоимость:",
  "Cost per chunk:": "Стоимость за фрагмент:",
  "Cost per cycle:": "Стоимость за цикл:",
  "Base time:": "Базовое время:",
  "Effective:": "Эффективно:",
  "Progress:": "Прогресс:",
  "When complete:": "После завершения:",
  "No foundries crafting T": "Нет литейных, крафтящих T",
  "Crafting Slot": "Слот крафта",
  "Craft Speed": "Скорость крафта",
  "Hide crafted": "Скрыть созданные",
  "Stop Production": "Остановить производство",
  "Tip: right click to set recipe for all slots. Right clicking on a crafting slot clears it.": "Подсказка: ПКМ задает рецепт для всех слотов. ПКМ по слоту крафта очищает его.",

  // Singularities / milestones
  "Singularity Points": "Очки сингулярности",
  "SP": "ОС",
  "Base SP": "Базовые ОС",
  "SP Calculation": "Расчет ОС",
  "Total": "Итого",
  "Total:": "Итого:",
  "Current:": "Текущее:",
  "Current": "Текущее",
  "Currently": "Сейчас",
  "Currently:": "Сейчас:",
  "Next:": "Далее:",
  "Next Milestone": "Следующий этап",
  "Hide completed": "Скрыть выполненные",
  "Milestones": "Этапы",
  "Milestone Gotten!": "Этап получен!",
  "Completed": "Выполнено",
  "Perform Singularity": "Выполнить сингулярность",
  "Break Singularity": "Пробить сингулярность",
  "What Persists": "Что сохраняется",
  "What Resets": "Что сбрасывается",
  "Remove 1e27 mana cap": "Убрать предел маны 1e27",
  "Mana is no longer capped at 1e27. Gain more SP per singularity based on how far past the cap you go.": "Мана больше не ограничена 1e27. ОС за сингулярность растут в зависимости от того, насколько вы превысили предел.",

  // Upgrade text snippets
  "Speed Boost (free)": "Буст скорости (бесплатно)",
  "Global Speed": "Глобальная скорость",
  "Global Yield": "Глобальный выход",
  "Yield Bonus": "Бонус выхода",
  "Speed Bonus": "Бонус скорости",
  "Mastery Bonuses": "Бонусы мастерства",
  "Combat bonuses:": "Боевые бонусы:",
  "Affects: T": "Влияет на: T",
  "Impact (": "Влияние (",
  "Effect": "Эффект",
  "Reward": "Награда",
  "Goal:": "Цель:",
  "Start": "Старт",
  "Exit Early": "Выйти раньше",
  "Finish": "Завершить",
  "MAX": "МАКС",
  "(CAPPED)": "(ПРЕДЕЛ)",
  "✓ Maxed": "✓ Макс.",

  // Misc
  "Display Settings": "Настройки отображения",
  "Preview:": "Предпросмотр:",
  "Show milestones": "Показывать этапы",
  "Show TPS": "Показывать TPS",
  "Show TPS meter at the bottom-left corner of the page.": "Показывать счетчик TPS в левом нижнем углу.",
  "Numbers above this value will display in scientific notation.": "Числа выше этого порога будут отображаться в научной нотации.",
  "Scientific Notation Threshold": "Порог научной нотации",
  "Align modifier units": "Выравнивать единицы модификаторов",
  "Align numbers to the beginning of the unit in modifier view.": "Выравнивать числа по началу единицы в окне модификаторов.",
  "How the game looks.": "Внешний вид игры.",
  "Clear": "Очистить",
  "Copy to Clipboard": "Скопировать в буфер",
  "Load File": "Загрузить файл",
  "Exported to clipboard": "Экспортировано в буфер",
  "Imported from file": "Импортировано из файла",
  "From": "Из",
  "Level": "Уровень",
  "Level Bonus": "Бонус уровня",
  "Level:": "Уровень:",
  "per craft": "за крафт",
  "damage": "урон",
  "mana": "мана",
  "speed": "скорость",
  "foundries": "литейные",
  "foundry": "литейная",
  "gems": "самоцветы",
  "cycles": "циклы",
  "chunks": "фрагменты",
  "No bonuses": "Нет бонусов"
};

// Prefix handling for mixed dynamic lines.
var cnPrefix = {
  "\n": "\n",
  " ": " ",
  "  ": "  ",
  "   ": "   ",
  "    ": "    ",
  "     ": "     ",
  "      ": "      ",
  "       ": "       ",
  "\t": "\t",
  "\n\t\t": "\n\t\t",
  "Current: +": "Текущее: +",
  "Current Endgame: ": "Текущий эндгейм: ",
  "Cost: ": "Стоимость: ",
  "Requires ": "Требуется ",
  "Show Milestones: ": "Показывать этапы: ",
  "Autosave: ": "Автосохранение: ",
  "Offline Prod: ": "Офлайн-прогресс: ",
  "Offline Time: ": "Офлайн-время: ",
  "Theme: ": "Тема: ",
  "Notation: ": "Нотация: ",
  "Toggle Music: ": "Музыка: ",
  "Animations: ": "Анимации: ",
  "Time Played: ": "Время в игре: ",
  "Space Background: ": "Фон космоса: ",
  "Shift-Click to Toggle Tooltips: ": "Shift+клик для подсказок: ",
  "Cost per chunk: ": "Стоимость за фрагмент: "
};

// Postfix handling for common suffixes.
var cnPostfix = {
  " ": " ",
  "  ": "  ",
  "   ": "   ",
  "    ": "    ",
  "     ": "     ",
  "      ": "      ",
  "       ": "       ",
  "\n": "\n",
  "\t": "\t",
  "/sec)": "/с)",
  "/s)": "/с)",
  " mana": " маны",
  " cores": " ядер",
  " points": " очков",
  " tiers": " уровней",
  " I": " I",
  " II": " II",
  " III": " III",
  " IV": " IV",
  " V": " V",
  " VI": " VI",
  " VII": " VII",
  " VIII": " VIII",
  " IX": " IX",
  " X": " X"
};

// Exclusion list for pure numbers/time/formats.
var cnExcludeWhole = [
  /^(\d+)$/,
  /^\s*$/,
  /^([\d\.,]+)$/,
  /^([\d\.,]+)e([\d\.,]+)$/,
  /^([\d\.,]+)e\+([\d\.,]+)$/,
  /^([\d\.,]+)\%$/,
  /^\+([\d\.,]+)\%$/,
  /^\-([\d\.,]+)\%$/,
  /^x([\d\.,]+)$/,
  /^×([\d\.,]+)$/,
  /^([\d\.,]+)x$/,
  /^\$([\d\.,]+)$/,
  /^([\d\.,]+)\/([\d\.,]+)$/,
  /^([\d\.,]+) \/ ([\d\.,]+)$/,
  /^([\d\.,]+):([\d\.,]+)$/,
  /^([\d\.,]+):([\d\.,]+):([\d\.,]+)$/,
  /^([\d\.,]+)s$/,
  /^([\d\.,]+)m$/,
  /^([\d\.,]+)h$/,
  /^([\d\.,]+)d$/,
  /^T([\d\.,]+)$/,
  /^T([\d\.,]+)\-T([\d\.,]+)$/,
  /^Lv\.([\d\.,]+)$/,
  /^[\u4E00-\u9FA5]+$/
];

var cnExcludePostfix = [];

// Dynamic text replacements with values.
var cnRegReplace = new Map([
  [/^([\d\.]+)\/sec$/, "$1/с"],
  [/^([\d\.]+)\/s$/, "$1/с"],
  [/^\(\+([\d\.]+)\/s\)$/, "(+$1/с)"],
  [/^\+([\d\.]+)\/s$/, "+$1/с"],
  [/^\-([\d\.]+)\/s$/, "-$1/с"],
  [/^\+([\d\.]+)\/min$/, "+$1/мин"],
  [/^\-([\d\.]+)\/min$/, "-$1/мин"],
  [/^([\d\.]+)k\/s$/, "$1k/с"],
  [/^\+([\d\.]+)k\/s$/, "+$1k/с"],
  [/^\-([\d\.]+)k\/s$/, "-$1k/с"],
  [/^\+([\d\.]+)m\/s$/, "+$1m/с"],
  [/^\-([\d\.]+)m\/s$/, "-$1m/с"],
  [/^\+([\d\.]+)b\/s$/, "+$1b/с"],
  [/^\-([\d\.]+)b\/s$/, "-$1b/с"],
  [/^\+([\d\.]+)t\/s$/, "+$1t/с"],
  [/^([\d\.]+) OOMs\/sec$/, "$1 OOM/с"],
  [/^([\d\.,]+) OOMs\/sec$/, "$1 OOM/с"],
  [/^([\d\.]+)e([\d\.,]+)\/sec$/, "$1e$2/с"],

  [/^You have (.+) points$/, "У вас $1 очков"],
  [/^Next at (.+) points$/, "Следующее на $1 очках"],
  [/^Cost: (.+) points$/, "Стоимость: $1 очков"],
  [/^Req: (.+) elves$/, "Требуется: $1 эльфов"],
  [/^Req: (.+) \/ (.+) elves$/, "Требуется: $1 / $2 эльфов"],
  [/^Generates ([\d\.]+) mana\/sec$/, "Генерирует $1 маны/с"],
  [/^requires ([\d\.]+) more research points$/, "Требуется еще $1 очков исследования"],
  [/^([\d\.]+)e([\d\.,]+) points$/, "$1e$2 очков"],

  [/^([\d\.]+)x craft speed$/, "$1x скорость крафта"],
  [/^([\d\.]+)x global crafting speed$/, "$1x глобальная скорость крафта"],
  [/^([\d\.]+)x T([\d\.]+) speed, ([\d\.]+)x yield per level$/, "$1x скорость T$2, $3x выход за уровень"],
  [/^([\d\.]+)x speed, ([\d\.]+)x yield for T([\d\.]+)\-T([\d\.]+)$/, "$1x скорость, $2x выход для T$3-T$4"],
  [/^All scale ([\d\.]+)x per level$/, "Все масштабируется на $1x за уровень"],
  [/^([\d\.]+)x SP earned per level$/, "$1x ОС за уровень"],

  [/^([\d\.]+) HP\/s regen, ([\d\.]+)x HP, ([\d\.]+)x attack speed$/, "$1 реген HP/с, $2x HP, $3x скорость атаки"],
  [/^([\d\.]+) HP\/s regen, ([\d\.]+)x HP, ([\d\.]+)x attack speed, ([\d\.]+)x damage$/, "$1 реген HP/с, $2x HP, $3x скорость атаки, $4x урон"],
  [/^×([\d\.]+) global \(([\d\.]+)x\)$/, "×$1 глобально ($2x)"],
  [/^×([\d\.]+) damage \(([\d\.]+)x\)$/, "×$1 урон ($2x)"],
  [/^×([\d\.]+) Damage \(([\d\.]+)x\)$/, "×$1 урон ($2x)"],
  [/^×([\d\.]+) HP \(([\d\.]+)x\)$/, "×$1 HP ($2x)"],
  [/^×([\d\.]+) attack speed \(([\d\.]+)x\)$/, "×$1 скорость атаки ($2x)"],
  [/^×([\d\.]+) Speed \(([\d\.]+)x\)$/, "×$1 скорость ($2x)"],
  [/^×([\d\.]+) mana \(([\d\.]+)x\)$/, "×$1 мана ($2x)"],
  [/^\-([\d\.]+)s revive \(([\d\.]+)s\)$/, "-$1с возрождение ($2с)"],
  [/^\+([\d\.]+) slot \(\+([\d\.]+) total\)$/, "+$1 слот (+$2 всего)"],

  [/^\+([\d\.]+)\% global speed per level$/, "+$1% глобальной скорости за уровень"],
  [/^\+([\d\.]+)\% global yield per level$/, "+$1% глобального выхода за уровень"],
  [/^\+([\d\.]+)\% energy core drops per level$/, "+$1% выпадения энергоядер за уровень"],
  [/^\+([\d\.]+)\% prism effectiveness per level$/, "+$1% эффективности призм за уровень"],
  [/^\+([\d\.]+)\% artifact effectiveness per level$/, "+$1% эффективности артефактов за уровень"],
  [/^\+([\d\.]+)\% singularity points per level$/, "+$1% очков сингулярности за уровень"],
  [/^\+([\d\.]+)\% mana multiplier$/, "+$1% множитель маны"],
  [/^\+([\d\.]+)\% base$/, "+$1% к базе"],

  [/^([\d\.]+)h ([\d\.]+)m$/, "$1ч $2м"],
  [/^([\d\.]+)m ([\d\.]+)s$/, "$1м $2с"],
  [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, "$1д $2ч $3м"],
  [/^Day ([\d\.,]+)$/, "День $1"],
  [/^Lv.([\d\.,]+)$/, "Ур. $1"],
  [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, "уровень $1 / $2"],
  [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, "уровень: $1 / $2"],
  [/^T([\d\.,]+) Lv([\d\.,]+)$/, "T$1 ур. $2"],
  [/^T([\d\.,]+) Mastery$/, "Мастерство T$1"],
  [/^T([\d\.,]+) Mastery: \+$/, "Мастерство T$1: +"],
  [/^T([\d\.,]+) Prism$/, "Призма T$1"],
  [/^T([\d\.,]+) Shield$/, "Щит T$1"],
  [/^T([\d\.,]+)-T([\d\.,]+) Automation$/, "Автоматизация T$1-T$2"],
  [/^Crush T([\d\.,]+) Gem$/, "Раздробить самоцвет T$1"],
  [/^Crush T([\d\.,]+) gems into T([\d\.,]+) dust$/, "Раздробить самоцветы T$1 в пыль T$2"]
]);
